#' Get project details (including tables)
#'
#' @inheritParams get_table_permissions
#'
#' @returns Data frame with project and tables associated
#' @keywords internal
#'
#' @family Opal
get_project_details <- function(x, project) {
  project |>
    lapply(function(p) {
      tryCatch(
        {
          # check if the given project exists
          project_exists(x, project = p)

          # retrieve tables for the given project
          project_tables <- get_project_tables(x, p)
          # check if any tables were found attached to the project
          if (length(project_tables) < 1) {
            return(tibble::tibble(project = p, table = NA))
          }
          tibble::tibble(
            project = p,
            table = project_tables
          )
        },
        error = function(e) {
          return(tibble::tibble(project = p, table = NA))
        }
      )
    }) |>
    dplyr::bind_rows() |>
    dplyr::filter(!is.na(table))
}

#' Get project resources
#'
#' Wrapper for [opalr::opal.project()].
#'
#' @inheritParams get_table_permissions
#'
#' @returns List of project resources
#' @keywords internal
#'
#' @family Opal
get_project_resources <- function(x, project) {
  # verify if project exists
  project_exists(x, project = project)

  # extract table names associated to `project`
  project_resources <- x |>
    opalr::opal.get("project", project, "resources") |>
    getElement("resource") |>
    # getElement("table") |>
    unlist()

  # if `project_resources` is missing or NULL, then print warning message
  if (all(is.na(project_resources)) || all(is.null(project_resources))) {
    warning(
      "The given `project`, does not have any resources associated!",
      call. = FALSE
    )

    # return empty list, invisibly
    return(invisible(list()))
  }

  # return project resources
  return(project_resources)
}

#' Get project tables
#'
#' Wrapper for [opalr::opal.project()].
#'
#' @inheritParams get_table_permissions
#'
#' @returns List of project tables
#' @keywords internal
#'
#' @family Opal
get_project_tables <- function(x, project) {
  # verify if project exists
  project_exists(x, project = project)

  # extract table names associated to `project`
  project_tables <- opalr::opal.project(x, project) |>
    getElement("datasource") |>
    getElement("table") |>
    unlist()

  # verify if `project_tables` is missing or NULL, if so, print warning message
  if (all(is.na(project_tables)) || all(is.null(project_tables))) {
    warning(
      "The given `project`, does not have any tables associated!",
      call. = FALSE
    )

    # return empty list, invisibly
    return(invisible(list()))
  }

  # return project tables
  return(project_tables)
}

#' Get table permissions
#'
#' Wrapper for the [opalr::opal.table_perm()] function.
#'
#' @inheritParams validate_opal_con
#' @param project String with project name.
#' @param tables String (or vector of strings) with table names for the given
#'     project.
#'
#' @returns Data frame with permissions for each table in `tables`.
#' @keywords internal
#'
#' @family Opal
get_table_permissions <- function(x, project, tables) {
  seq_along(tables) |>
    lapply(function(j) {
      tryCatch(
        {
          tibble::tibble(
            project = project,
            table = tables[j],
            # get permissions for each dataset inside each project
            opalr::opal.table_perm(x, project, tables[j])
          )
        },
        error = function(e) {
          if (grepl("HTTP 403", e$message)) {
            stop(
              "The provided connection does not have access to retrieve ",
              "table permissions!",
              call. = FALSE
            )
          } else if (grepl("HTTP 404", e$message)) {
            warning(
              "Error when retrieving permissions for ",
              paste0(project, ".", tables[j], "!"),
              call. = FALSE
            )
          } else {
            warning(e$message, call. = FALSE)
          }

          # return empty tibble, only with `project` and `table` details
          return(tibble::tibble(
            project = project,
            table = tables[j]
          ))
        }
      )
    }) |>
    # combine results from the permissions for each table
    dplyr::bind_rows()
}

#' Flatten user permission entities
#'
#' @param x List with entities, generated by [user_perm_entity()].
#'
#' @returns Tibble with properties of the entities.
#' @keywords internal
flatten_user_perm_entity <- function(x) {
  # local bindings
  agent <- object <- table_id <- user_id <- NULL

  # flatten list of entities
  x_tbl <- x |>
    lapply(tibble::as_tibble, .name_repair = "minimal") |>
    dplyr::bind_rows()
  # check there were any entities found in the previous step
  if (nrow(x_tbl) == 0) {
    return(NULL)
  }
  # edit tibble with entities
  x_tbl |>
    dplyr::rename(
      id = "@id",
      type = "@type",
      user_id = agent,
      table_id = object
    ) |>
    dplyr::mutate(
      user_id = unlist(user_id),
      table_id = unlist(table_id),
    ) |>
    # add permission field, based on `type`
    dplyr::mutate(
      permission = dplyr::case_when(
        type == "ReadAction" ~ "read",
        type == "WriteAction" ~ "write",
        type == "ControlAction" ~ "administrate",
        TRUE ~ NA_character_
      )
    )
}

#' Verify if connection was created by an administrative user
#'
#' @inheritParams validate_opal_con
#'
#' @returns Boolean flag to indicate whether the given connection was created
#'     by an administrative user.
#' @keywords internal
is_opal_admin_con <- function(x) {
  # validate connection
  validate_opal_con(x)

  # extract the user profile, `uprofile` from the connection object
  uprofile <- getElement(x, "uprofile")

  # extract logged in user's groups
  groups <- getElement(uprofile, "groups") |>
    sapply(unlist)

  # check if the user has admin in their groups
  if ("admin" %in% groups) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

#' Update datasets linked to a project
#'
#' Update datasets linked to a project (`hasPart`)
#'
#' @inheritParams safe_data
#' @param ds_ids Vector with `@id`s of the datasets to be linked to `project`
#'
#' @returns Update RO-Crate with updated project entity
#' @keywords internal
update_project_datasets <- function(rocrate, project, ds_ids) {
  # attempt to retrieve the project entities to link up the IDs to the project
  # this only valid if safe_project is called before safe_data
  suppressWarnings({
    project_ents <- rocrate |>
      rocrateR::get_entity(type = "Project") |>
      # only keep entity for `project`
      Filter(f = \(x) getElement(x, "name") == project)
  })

  # if any entity was found, then filter to keep those for which their @id
  # starts with `project_id_suffix` as set by `safe_project()`:
  if (length(project_ents) == 1 && !is.null(project)) {
    # extract the `hasPart` section
    has_part <- project_ents |>
      sapply("[[", "hasPart") |>
      unlist()

    # update the `hasPart` section
    rocrate <- rocrate |>
      rocrateR::add_entity_value(
        id = project_ents[[1]]["@id"],
        key = "hasPart",
        value = c(has_part, ds_ids) |>
          unique() |>
          lapply(\(id) list(`@id` = id)),
        overwrite = TRUE
      )
  }

  # return update RO-Crate
  return(rocrate)
}

#' Create user permission entities
#'
#' @param user String with user name.
#' @param user_id String with user `@id`.
#' @param table String with dataset/table name.
#' @param table_id String with dataset/table `@id`.
#' @param permission String with permission ('view', 'view-values', 'edit',
#'     'edit-values' OR 'administrate').
#' @param ... Other additional values.
#'
#' @returns List of [rocrateR::entity] objects
#' @keywords internal
user_perm_entity <- function(user, user_id, table, table_id, permission, ...) {
  # set local bindings
  description <- type <- NULL
  action_status <- "PotentialActionStatus"
  agent <- list(list(`@id` = user_id))
  object <- list(list(`@id` = table_id))

  # create combined @id
  comb_id <- paste0("#perm:", digest::digest(paste0(user, "-", table)))

  # update combine @id, @type and description based on permission
  if (permission == "view") {
    comb_id <- paste0(comb_id, "-dict-summary-read")
    type <- "ReadAction"
    description <- "User may view table dictionary and summary statistics only; access to individual values is restricted."
  } else if (permission == "view-values") {
    comb_id <- paste0(comb_id, "-read-all")
    type <- "ReadAction"
    description <- "User may view table dictionary and all individual values."
  } else if (permission == "edit") {
    comb_id <- paste0(comb_id, c("-write-dict", "-summary-read"))
    type <- c("WriteAction", "ReadAction")
    description <- c(
      "User may edit the table dictionary but cannot view individual values.",
      "User may view summary statistics only; access to individual values is restricted."
    )
  } else if (permission == "edit-values") {
    comb_id <- paste0(comb_id, c("-write-dict", "-read-all"))
    type <- c("WriteAction", "ReadAction")
    description <- c(
      "User may edit the table dictionary.",
      "User may view table dictionary and all individual values."
    )
  } else if (permission == "administrate") {
    comb_id <- paste0(comb_id, "-admin-table")
    type <- "ControlAction"
    description <- "User has full administrative rights: view/edit dictionary and view/edit individual values."
  } else {
    return(NULL)
  }

  # create entity objects
  permission_entities_tbl <- tibble::tibble(
    id = comb_id,
    type = type,
    agent = agent,
    object = object,
    actionStatus = action_status,
    description = description
  )

  # seq_len(nrow(permission_entities_tbl)) |>
  #   lapply(function(i) {
  #     rocrateR::entity(permission_entities_tbl$`id`[i],
  #                      type = permission_entities_tbl$type[i])
  #   })
  purrr::pmap(permission_entities_tbl, rocrateR::entity)
  # rocrateR::entity(as.list(permission_entities_tbl))
}

#' Validate OBiBa's Opal connection
#'
#' @param x Connection to OBiBa's Opal server (see [opalr::opal.login()]).
#'
#' @returns Nothing, call for its side effect.
#' @keywords internal
validate_opal_con <- function(x) {
  tryCatch(
    {
      status <- xptr::is_null_xptr(x$handle$handle)
      if (status) {
        stop("The given connection is not valid!", call. = FALSE)
      }
    },
    error = function(e) {
      stop("The given connection is not valid!", call. = FALSE)
    }
  )
}
